### PR TITLE
added outdir param and simple resume functionality

### PR DESCRIPTION
**Pull request by joehagmann**
added output dir parameter, plus simple resume functionality: each step is executed only if output file not present or zero size

### CODE REVIEW

**Comment by superjox** [comment]
The reason for the output dir was that some options (e.g. smoothxg's -G) don't make it to the output file name, so different runs with different parameters would write into the same output file. An alternative is of course to include all params into the file name, but an output dir is imho more scalable and easier to maintain.

**Comment by ekg** [comment]
This looks great. I'm considering using snakemake or something similar to implement the pipeline, to allow for restarts and support cluster jobs.

**Comment by subwaystation** [comment]
The Nextflow port is now a work in progress https://github.com/nf-core/pangenome.

Will support all that you had in mind and you can watch your running pipeline using https://tower.nf/.

**Comment by joehagmann** [comment]
I will do a separate PR incl. yml log file, and am closing this one

**Pull request closed without merging**
