### PR TITLE
Consensus less

### PR DESCRIPTION
**Pull request by ekg**
Don't require consensus graph and MAF output. Make these optionally enabled with the -C and -F parameters.

Update to nice versions of smoothxg and wfmash.

### CODE REVIEW

**Comment by subwaystation** [comment]
I can't reproduce an `exit 1` locally using the docker image build from this PR.

**Comment by ekg** [comment]
I'm quite close to merging through this failure. I can't reproduce it either.

**Comment by subwaystation** [comment]
https://github.com/actions/virtual-environments/issues/1279

I suspect it's some kind of GithubActions thing related to our bash script?

**Comment by AndreaGuarracino** [comment]
`pigz` was failing in finding the MAF file. Now it is fixed.

**Pull request merged**
