### PR TITLE
fastify the yeet

### PR DESCRIPTION
**Pull request by ekg**
Setting up for a release based on new versions of edyeet and smoothxg.

Note the addition of scostumato block merging in smoothxg by default. Not sure if this is good or should be configurable.

### CODE REVIEW

**Comment by ekg** [comment]
This needs to get synced up with new versions of the various repos.

**Comment by subwaystation** [comment]
Before we merge this, I want to add tests for `wfmash`, too.

**Comment by subwaystation** [comment]
Thanks @AndreaGuarracino !

**Comment by ekg** [comment]
wfmash is nearly ready. Doing final tests now.

**Comment by AndreaGuarracino** [comment]
`superxg` is ready too

**Pull request merged**
