### PR TITLE
Emit tools' version in the LOG/YAML output

### PR DESCRIPTION
**Pull request by AndreaGuarracino**
This helps reproducibility and debugging.

```
Starting pggb on 11-10-2022_09:59:47

Command: /home/guarracino/git/pggb/pggb -i data/HLA/DRB1-3123.fa.gz -p 70 -s 3000 -G 2000 -n 10 -o drib1

PARAMETERS

general:
  input-fasta:        data/HLA/DRB1-3123.fa.gz
  output-dir:         drib1
  temp-dir:           drib1
  resume:             false
  compress:           false
  threads:            12
  poa_threads:        12
wfmash:
  version:            v0.10.0-6-g5791c12
  segment-length:     3000
  block-length:       25000
  map-pct-id:         70
  n-mappings:         10
  no-splits:          false
  sparse-map:         false
  mash-kmer:          19
  mash-kmer-thres:    0.001
  exclude-delim:      false
  no-merge-segments:  false
seqwish:
  version:            v0.7.7-2-gf362f6f
  min-match-len:      19
  sparse-factor:      0
  transclose-batch:   10000000
smoothxg:
  version:            v0.6.7-5-g0c04e30
  skip-normalization: false
  n-haps:             10
  path-jump-max:      0
  edge-jump-max:      0
  poa-length-target:  2000
  poa-params:         1,19,39,3,81,1
  poa_padding:        0.001
  run_abpoa:          false
  run_global_poa:     false
  pad-max-depth:      100
  write-maf:          false
  consensus-spec:     false
  consensus-prefix:   Consensus_
  block-id-min:       .7000
  block-ratio-min:    0
odgi:
  version:            v0.8.1-4-gc8717fc
  viz:                true
  layout:             true
  stats:              false
gfaffix:
  version:            v0.1.4
  reduce-redundancy:  true
vg:
  version:            v1.43.0
  deconstruct:        false
reporting:
  version:            v1.11
  multiqc:            false

Running pggb

...
```

### CODE REVIEW

**Comment by AndreaGuarracino** [comment]
multiqc is annoyingly slow in giving us the version, so it will be not put in the LOG/YAML, unless contrary opinions
```
\time multiqc --version | cut -f 3 -d ' '
1.12
0.49user 0.02system 0:00.52elapsed 100%CPU (0avgtext+0avgdata 79416maxresident)k
```

**Comment by subwaystation** [comment]
YES OF COURSE WE WANT IT.

**Comment by ekg** [comment]
Seems okay to add it, no?

**Comment by AndreaGuarracino** [comment]
Okay, we will add it then. It might get annoying for quick tests, but the delayed start will probably be not crucial for general users.

**Pull request merged**
